### ISSUE TITLE
When will the dataset open？

### ISSUE THREAD

**Issue by 1244632315** [tanvirnwu/HazeSpace2M#1]
when will this dataset open? thanks for your contribution 😄

**Comment by tanvirnwu** [comment]
Hello,

Thank you for your interest and question. The dataset is quite large, and we are currently in discussions with the Hugging Face team to explore hosting options for making it publicly accessible. We are optimistic that the dataset will soon be available through the Hugging Face Hub.

We appreciate your patience and support. Please stay tuned for updates!

Best regards

**Comment by tanvirnwu** [comment]
Hello,

Thanks for your interest and stay patient for the HazeSpace2M dataset. We have managed to upload the subsets of the HazeSpace2M dataset. You can access it now _[HERE](https://huggingface.co/datasets/tanvirnwu/HazeSpace2M/tree/main)_.

Please let us know if you face any issues downloading or using it. Please do not forget to cite the [HazeSpace2M paper](https://dl.acm.org/doi/abs/10.1145/3664647.3681382).



Good luck with your research. 

Regards,
Tanvir
