### ISSUE TITLE
Pre trained weights release date

### ISSUE THREAD

**Issue by Liampour** [tanvirnwu/HazeSpace2M#2]
Hello,
congratulations for your work based on the paper seems very promising!!
I noticed that it has been several months since you published the code but there is no pre-trained model available.
Have you set a date for publishing the pre-trained models? or may have you reconsidered their publication? 

Thank you

**Comment by tanvirnwu** [comment]
Dear Liampour,

Thank you for your interest and kind words regarding our work. We are pleased to inform you that the pre-trained weights for the best-performing classifiers and dehazing models have now been uploaded. Kindly revisit the repository to access the newly added files.

Best regards
